### ISSUE TITLE
0.1.5.6 doesn't support SpoolManger Window

### ISSUE THREAD

**Issue by diedder** [LazeMSS/OctoPrint-UICustomizer#143]
together with SpoolManager Plugin (1.3.4) the popup window for editing spools isn't shown completely. Some mandatory fields (such as weight) are not visible so the plugin could not be used.

see screenshots with enabled and disabled UI customizer attached
<img width="1049" alt="disabled" src="https://user-images.githubusercontent.com/25912001/115141116-faba6900-a03a-11eb-92d3-916e713e0531.png">
<img width="1026" alt="enabled" src="https://user-images.githubusercontent.com/25912001/115141119-fc842c80-a03a-11eb-8a3e-491370e4f949.png">

thanks in advance!

**Comment by LazeMSS** [comment]
No really the spool manager is pushing the envelope on how much stuff you can cram into a overlay dialog and when bootstrap default responsive CSS is added by UI customizer it breaks. But I think it is fixed in some of the latest versions of spool manager.

I'm hoping at some point to help with a rewrite of the UI for spool manager.

Btw what screen resolution are you using?

**Comment by diedder** [comment]
my screen on laptop is MBP 13,3-Zoll (2560 × 1600)

**Comment by LazeMSS** [comment]
Strange that should be plenty screen estate. I don't have any problems. Will test again

**Comment by LazeMSS** [comment]
@diedder I can't recreate - can you try again and maybe clear browser cache.

**Comment by LazeMSS** [comment]
Found the bug - https://github.com/OllisGit/OctoPrint-SpoolManager/issues/142#issuecomment-825601100

I won't fix - should be fixed in the SpoolManager plugin

**Comment by diedder** [comment]
Thank you anyway!

**Comment by LazeMSS** [comment]
I have included a fix in the next release but i hope the main author will add this as well

**Comment by lightmaster** [comment]
@LazeMSS You sir are a hero. 👏
