### ISSUE TITLE
Touch UI Compatibility 

### ISSUE THREAD

**Issue by RagingHog55** [LazeMSS/OctoPrint-UICustomizer#161]
So this could be just me, but when viewing Octoprint on a desktop/laptop the TouchUI menu is in the middle of the top bar along with Progress: 0% Layer: - of - Height: - of -mm. However when i go over to my raspberry pi 7" touchscreen next to the printer this is no longer there. Is there a way to get this functionality on a smaller screen?

**Comment by LazeMSS** [comment]
The problem is touch UI and UI customizer collides.

When running it on Touch screen always add: #touch to the URL. So the URL to use on the 7" Touch is : http://IP of RPI#touch for example http://192.168.1.1/#touch

This hopefully fix it.

But I would encourage you to use one of the dedicated UIs for the Touch screens like OctoDash and remove touch UI.

**Comment by RagingHog55** [comment]
Thank you, i hadn't looked for alternatives to TouchUI in quite sometime. I like your UI and just switched to it and noticed touchUI no longer worked. I am in the process of getting OctoDash installed! Thanks!

**Comment by LazeMSS** [comment]
Great closing now then b
