### ISSUE TITLE
Setting Icon not able to be selected

### ISSUE THREAD

**Issue by kelvindavis** [LazeMSS/OctoPrint-UICustomizer#188]
After todays update to UI Customizer, I am unable to select the setting icon (wrench).  If I go into safe mode and turn off UI Customizer, I am able to select it as normal.  Was working fine up until todays update.

**Comment by LazeMSS** [comment]
Do you have responsive mode enabled or not?

**Comment by endurance1968** [comment]
Same issue here. I updated on 2 of three printers - the updated ones are showing the issue the one on previous version (1.6.4) is working as expected.
Where to enable/disable responsive mode?

**Comment by LazeMSS** [comment]
In settings :/ Working on a fix - but try making the window wider - this should fix and allow settings tool.

**Comment by endurance1968** [comment]
Oh great in settings :)
Wider does not help -even more than 3400 pixels wide, also shrinking to min and chnaging back to wide does not change the behaviour here.

**Comment by LazeMSS** [comment]
That's really strange - what browser?

**Comment by kelvindavis** [comment]
Wider did not work for me and I have used Safari and chrome

**Comment by endurance1968** [comment]
FF - but making it smaller so you get the menu instead of navbar items allows you to access the settings.

**Comment by LazeMSS** [comment]
Working fine on chrome for me - will test in FF

**Comment by LazeMSS** [comment]
@endurance1968  could you try and go into settings - and UI Customizer settings and click report a bug so I can get the data

**Comment by kelvindavis** [comment]
I can do that as well after the print I’m doing finishes

**Comment by endurance1968** [comment]
deactivating resp mode works - but you have to refresh browser manually as all buttons are gone otherwise.

## Description
**ENTER DESCRIPTION HERE
Describe your problem?
What is the problem?
Can you recreate it?
Did you try disabling plugins?
Did you remember to update the subject?**
<hr>

**Plugins installed**
- **UI Customizer[uicustomizer] v0.1.6.6**
- Top Temp[toptemp] v0.0.1.4
- Translate Model Plugin[translatemodel] v0.2.0
- Printer Stats[stats] v3.1.2
- Simple Emergency Stop[simpleemergencystop] v1.0.5
- PrintTimeGenius Plugin[PrintTimeGenius] v2.2.8
- Draggable Files[draggable_files] v1.0.4
- Dashboard[dashboard] v1.18.3
- Octolapse[octolapse] v0.4.1
- OctoKlipper[klipper] v0.3.8.3
- Filament Sensor Simplified[filamentsensorsimplified] v0.2.3
- DisplayLayerProgress Plugin[DisplayLayerProgress] v1.26.0
- Bed Visualizer[bedlevelvisualizer] v1.1.0


**UI Customizer settings**
- addWebCamZoom: true
- centerTopIcons: true
- compactMenu: true
- compressTempControls: true
- disableTermInactive: false
- filesFullHeight: true
- fixedFooter: true
- fixedHeader: true
- fluidLayout: true
- gcodeFullWidth: false
- hideGraphBackground: true
- hideMainCam: false
- mainTabsCustomize: true
- navbarplugintempfix: false
- responsiveMode: false
- saveAccordions: false
- themeLocal: false


**Software versions**
- OctoPrint 1.6.1
- Python 3.7.3
- OctoPi 0.18.0

**Browser**
- Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:91.0) Gecko/20100101 Firefox/91.0

**Comment by LazeMSS** [comment]
Do you know what theme your running and can you post a screenshot maybe?

**Comment by endurance1968** [comment]
Screenshot in a few miinutes

Second printer
**Plugins installed**
- **UI Customizer[uicustomizer] v0.1.6.6**
- Top Temp[toptemp] v0.0.1.4
- Themeify[themeify] v1.2.2
- Translate Model Plugin[translatemodel] v0.2.0
- Tab Order[taborder] v0.5.12
- Printer Stats[stats] v3.1.2
- PrintTimeGenius Plugin[PrintTimeGenius] v2.2.8
- LightsOut[lightsout] v0.1.2
- Fix CBD Firmware Plugin[fixcbdfirmware] v0.4.0
- Filament Sensor Reloaded[filamentreload] v1.3.4
- Draggable Files[draggable_files] v1.0.4
- Dashboard[dashboard] v1.18.3
- Octolapse[octolapse] v0.4.1
- DisplayLayerProgress Plugin[DisplayLayerProgress] v1.26.0


**UI Customizer settings**
- addWebCamZoom: true
- centerTopIcons: true
- compactMenu: true
- compressTempControls: true
- disableTermInactive: false
- filesFullHeight: true
- fixedFooter: true
- fixedHeader: true
- fluidLayout: true
- gcodeFullWidth: false
- hideGraphBackground: true
- hideMainCam: false
- mainTabsCustomize: true
- navbarplugintempfix: true
- responsiveMode: true
- saveAccordions: false
- themeLocal: false


**Software versions**
- OctoPrint 1.6.1
- Python 3.7.3
- OctoPi 0.17.0

**Browser**
- Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:91.0) Gecko/20100101 Firefox/91.0

**Comment by LazeMSS** [comment]
Btw. Themify and Tab Order should not be needed

**Comment by kelvindavis** [comment]
I was using slate

**Comment by endurance1968** [comment]
![2021-09-01_07h12_17](https://user-images.githubusercontent.com/38796027/131615695-f98e8d27-6288-4d17-9b5b-e6a1cb45961a.png)
![2021-09-01_07h12_55](https://user-images.githubusercontent.com/38796027/131615700-c988ffc3-50f6-4905-904d-d1ee468e4af8.png)

**Comment by endurance1968** [comment]
>Btw. Themify and Tab Order should not be needed
okido - will deinstall

**Comment by LazeMSS** [comment]
@endurance1968  can you post a screenshot of the main ui ?
And if possible run this command from the developer console (F12):
$('div.UIHeaderWrap').css('background-color','#ff0000')

**Comment by kelvindavis** [comment]
I have joined it but new to discord

**Comment by LazeMSS** [comment]
@kelvindavis what name?

**Comment by kelvindavis** [comment]
OHKinkBear

**Comment by endurance1968** [comment]
I just joined discord.
![2021-09-01_07h39_42](https://user-images.githubusercontent.com/38796027/131617894-ad2d68f5-1c44-4944-827e-f8d0f4e0f969.png)

**Comment by LazeMSS** [comment]
yeah seems like something is wrong with the width of that overlay

**Comment by LazeMSS** [comment]
@endurance1968 do you have a user name?

**Comment by endurance1968** [comment]
endurance

**Comment by LazeMSS** [comment]
The bug has been found - long usernames DOOH

**Comment by endurance1968** [comment]
happy to test as soon as you have the update ready

**Comment by kelvindavis** [comment]
Let us know when and be happy to test

**Comment by LazeMSS** [comment]
Fixed in next release

**Comment by LazeMSS** [comment]
Out now - 0.1.6.7

**Comment by endurance1968** [comment]
Updated - and seems to work - thx
