### ISSUE TITLE
[Feature] Add compatibility with webcam iframe plugin

### ISSUE THREAD

**Issue by scmanjarrez** [LazeMSS/OctoPrint-UICustomizer#292]
~Octoprint doesn't work by default with webrtc~, but you can embed a stream using [webcam iframe plugin](https://plugins.octoprint.org/plugins/webcam_iframe/), which work very well but seems uncompatible with UI customizer, as it doesn't load the webcam stream.

**Comment by jneilliii** [comment]
> Octoprint doesn't work by default with webrtc

that's not quite true. OctoPrint does support webrtc, but the URL has to be entered in a specific way. it is however very finicky on what types of webrtc implementations work. the next release of OctoPrint 1.9.0 will extract the webcam from core OctoPrint into a plugin system and with a future release of OctoPi that integrates camera-streamer for webcam instead of mjpg you'll be able to natively connect webrtc as an option with [this](https://github.com/cp2004/OctoPrint-CameraStreamer-Control).
