### ISSUE TITLE
Request - Export/Import

### ISSUE THREAD

**Issue by PGlyre** [LazeMSS/OctoPrint-UICustomizer#46]
Export / Import function. 
It would have been easier for those who have several printers with OctoPrint and in the first place I think of configuration under "Main Tabs" #
![Request - UICustomizer](https://user-images.githubusercontent.com/25323238/103206454-2f73aa80-48fc-11eb-835e-ebbdff992a2b.jpg)

**Comment by LazeMSS** [comment]
You want an option to export the UI settings? That should not be that difficult.

**Comment by PGlyre** [comment]
Hi, I'm not the best at English, but you got me right. It was my wish and if you ask if you do not get an answer ....... I have full respect for developers like you and I do not have that kind of knowledge so therefore I submitted this proposal to you

**Comment by LazeMSS** [comment]
Just a quick update - im working on this - its not as easy as it might seem but I will fix it :)

**Comment by jaimieb29** [comment]
No problem, really appreciate your work thanks

Sent from my iPhone

On 8 Nov 2021, at 09:24, LazeMSS ***@***.***> wrote:

﻿
Just a quick update - im working on this - its not as easy as it might seem but I will fix it :)

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by LazeMSS** [comment]
90% done ;)

**Comment by LazeMSS** [comment]
Should now be included in the 0.1.8.0 release (https://github.com/LazeMSS/OctoPrint-UICustomizer/releases/tag/0.1.8.0) - please reopen if not working as expected.
